FROM python:3.10-slim

COPY ./recsys_app /code/app
COPY ./requirements-service.txt /code/requirements-service.txt

WORKDIR /code

RUN pip3 install --no-cache-dir -r requirements-service.txt

EXPOSE ${MAIN_APP_PORT}

CMD uvicorn app.recommendations_service:app --port ${MAIN_APP_PORT} --host 0.0.0.0